### PR TITLE
Added release notes page

### LINKED ISSUE #8: Release notes
Add a release notes page.

For now, it should contain a heading for each push to production with a list of things that were pushed.

This is to be a public-facing page, so keep it clean, don't mention customers, don't reveal secrets, and filter anything else that shouldn't be public.

### PR DESCRIPTION
**Pull request by armilam**
So I'm thinking this is what the release notes page should look like. Feel free to provide any feedback!

Also, here's what I'm thinking for the process of adding to the release notes:

1. A PR by DevA is merged (in the app repo) by DevB
2. DevA checks out the `release-notes` branch in the documentation repo (this repo)
3. DevA adds a line under the "NEXT RELEASE" section in `release-notes.md` to describe what was added/changed/fixed in the app
4. DevA pushes the `release-notes` branch back up to github
5. Some time later (after maybe a few PRs), DevC pushes the app to production
6. DevC checks out the `release-notes` branch in the documentation repo
7. DevC changes the title "NEXT RELEASE" to the current date and time in `release-notes.md`
8. DevC merges `release-notes` into `master` and pushes `master` back up to github
9. DevC creates a new `release-notes` branch and adds a new "NEXT RELEASE" section in `release-notes.md`

Those steps should only happen when a PR is merged that should be announced publicly.

What do you think?

Fixes #8

### CODE REVIEW

**Comment by armilam** [comment]
@kpascascio, I'd like your opinions here, as well.

**Comment by kpascascio** [comment]
I feel good about that process.

**Comment by stevegrossi** [comment]
Great work here—I love the page! As for the process, What would you think about skipping the "release-notes" branch and doing all this on master?

I'm interested in making these additional steps as easy as possible, which ideally means you can do them entirely through the Github web interface. As you have it, steps 2–4 can be done purely on Github, but steps 6–8 would either

- need to be pulled, merged, and pushed via the command line
- or we'd need to open a new PR for every release in order to merge via the Github web interface

This could be avoided if we just made these lightweight documentation changes directly to master through the Github editor and avoided merging. What do you think?

**Comment by armilam** [comment]
So it's decided! Updates to release notes will go like this:

If my change is something that should go in the release notes:
1. My PR was merged! Yay!
2. I go to Github and edit this file directly to add my change to the "Coming Soon" section directly in `master`.

1. It's time to push to production. Yay!
2. I push to production.
3. I go to Github and edit this file directly to change "Coming Soon" to the current date and time.
4. I also add a new "Coming Soon" section

Some time in the future, we will want to automate this process a little - perhaps with a rake task that goes something like `rake release`.

**Comment by kpascascio** [comment]
I found this to be cool from <a href= "https://www.mozilla.org/en-US/firefox/33.0.1/releasenotes/">Mozilla</a> Release Notes

image

**Comment by stevegrossi** [comment]
Yeah, the categorization is cool and useful. I've liked how our WYSIWYG editor's developers do the same: http://imperavi.com/redactor/log/

**Pull request merged**
