### PR TITLE
Add stubbing-related guidelines

### PR DESCRIPTION
**Pull request by stevegrossi**
Check out the changes made for a description (they should in principle be clear enough—if not, I should probably reword.)

### CODE REVIEW

**Comment by stevegrossi** [comment]
Thoughts, @lessonly/developers?

**Comment by armilam** [comment]
I agree with this word-for-word. I'll wait for feedback from @kpascascio and @TheAustinSeven before merging.

**Comment by kpascascio** [comment]
I also agree with this, I got to see the change when I reviewed @stevegrossi PR that had this as an example.

**Comment by armilam** [comment]
Well, we got one positive feedback and zero negative, so it's time to merge!

**Pull request merged**
