### PR TITLE
Add first draft git styleguide

### PR DESCRIPTION
**Pull request by joshmfrankel**
- Added a section detailing our branching strategy
- Started a section on commits and message best practices
- Configuration section for default settings
- Aliases added for quicker workflow

### CODE REVIEW

**Comment by joshmfrankel** [comment]
Things I would like to add:
* Aliases that other team members use
* As a team decide on a git comment message template
* More to come...

**Comment by stevegrossi** [comment]
We do have a lesson in the Learning Library about branching strategy: https://about.lesson.ly/library/lesson/8775-branching-strategy

We've not been super clear about what belongs in Lesson.ly and what belongs in our coding styleguide—might be a good time to discuss!

**Comment by joshmfrankel** [comment]
Excellent idea @stevegrossi. I brought up your question in the July 20th, team retro.

**Comment by joshmfrankel** [comment]
So it has literally been forever since this was discussed and due to new processes in Github we could probably update this and make it a lot better.

Specifically, when you have a feature branch with branches depending upon it and the feature branch becomes squashed, how can you properly rebase without running into merge conflicts.

**Pull request closed without merging**
