### PR TITLE
Document our usage of service objects with patterns

### PR DESCRIPTION
**Pull request by stevegrossi**
We're using this pattern a lot, to great effect. To familiarize new developers with it and to improve consistency in usage, I think it's worth adding to the styleguide.

Thoughts? @armilam, @kpascascio, @TheAustinSeven, @kyprifog

### CODE REVIEW

**Comment by stevegrossi** [comment]
In [a comment on another PR](https://github.com/lessonly/lesson.ly/pull/1065/files#r32652975), @kyprifog brought up some valid points about DRYness here, specifically around how the `self.perform` method does basically the same thing across all services that instantiate objects. It'd be great to extract this into a base `Service` class that our services could inherit from and get the `self.perform` method for free.

**Comment by armilam** [comment]
I think this is great. If we get agreement from the other devs, I'm happy to merge.

**Comment by stevegrossi** [comment]
Yeah, no rush on these styleguide additions. Unlike app PRs, for these I think it's important that everyone have the time to provide input.

**Comment by armilam** [comment]
@TheAustinSeven, @kpascascio, I'd like to point you guys as this again in case you forgot.

**Comment by stevegrossi** [comment]
I'm going to make one small change on line 41, removing the parens from the method call:

```
# Service objects are called with `ServiceName.perform()`
Service objects are called with `ServiceName.perform`
```

I'd intended that to suggest that you can pass arguments to `ServiceName.perform`, but as written it's incompatible with our Ruby styleguide and potentially confusing.

**Comment by TheAustinSeven** [comment]
I think it is very good, I agree that this should be merged.

**Pull request merged**
