### PR TITLE
Explicitly use booleans in conditionals

### PR DESCRIPTION
**Pull request by armilam**
Just like the text says, this adds clarity to the purpose of the condition.

### CODE REVIEW

**Comment by armilam** [comment]
@TheAustinSeven, @stevegrossi, a style guide addition for your consideration.

**Comment by stevegrossi** [comment]
A fine practice! :+1:

**Comment by TheAustinSeven** [comment]
I like this! It makes the code much easier to understand.

**Comment by kpascascio** [comment]
Nooice!

**Pull request merged**
